removed another unreliable test
in the Github action it complains:

1) Tests\ExampleTest\FoafinfoTest::testNjh
Exception: Failed to run script (255): PHP Warning:  fsockopen(): Unable
to connect to ssl://www.aelius.com:443 (Connection timed out) in
/home/runner/work/easyrdf/easyrdf/lib/Http/Client.php on line 435
PHP Fatal error:  Uncaught EasyRdf\Exception: Unable to connect to
ssl://www.aelius.com:443 (Connection timed out) in
/home/runner/work/easyrdf/easyrdf/lib/Http/Client.php:437
Stack trace:
EasyRdf\Http\Client->request()
EasyRdf\Graph->load()
EasyRdf\Graph::newAndLoad()
require('...')
thrown in /home/runner/work/easyrdf/easyrdf/lib/Http/Client.php on
line 437
<html>
<head><title>EasyRdf FOAF Info Example</title></head>
<body>
<h1>EasyRdf FOAF Info Example</h1>

<form method="get"
action="/home/runner/work/easyrdf/easyrdf/test/cli_example_wrapper.php"><input
type="text" name="uri" id="uri"
value="https://www.aelius.com/njh/foaf.rdf" size="50" /><input
type="submit" value="Submit" /></form>

/home/runner/work/easyrdf/easyrdf/test/TestHelper.php:134
/home/runner/work/easyrdf/easyrdf/tests/ExampleTest/FoafinfoTest.php:57